### ISSUE TITLE
Got error during installation, can not start server

### ISSUE THREAD

**Issue by tinhbuon1102** [openboxes/openboxes#2124] opened 2020-12-26 02:44 UTC
Hello, i followed the instruction to setup openboxes, after waited for few hours to run liquibase i got the error like this :

`2020-12-26 08:50:59,816 [main] ERROR context.GrailsContextLoader  - Error executing bootstraps: Validation Error(s) occurred during save():
- Field error in object 'org.pih.warehouse.core.Location' on field 'organization': rejected value [null]; codes [org.pih.warehouse.core.Location.organization.validator.error.org.pih.warehouse.core.Location.organization,org.pih.warehouse.core.Location.organization.validator.error.organization,org.pih.warehouse.core.Location.organization.validator.error.org.pih.warehouse.core.Organization,org.pih.warehouse.core.Location.organization.validator.error,location.organization.validator.error.org.pih.warehouse.core.Location.organization,location.organization.validator.error.organization,location.organization.validator.error.org.pih.warehouse.core.Organization,location.organization.validator.error,org.pih.warehouse.core.Location.organization.validator.required.org.pih.warehouse.core.Location.organization,org.pih.warehouse.core.Location.organization.validator.required.organization,org.pih.warehouse.core.Location.organization.validator.required.org.pih.warehouse.core.Organization,org.pih.warehouse.core.Location.organization.validator.required,location.organization.validator.required.org.pih.warehouse.core.Location.organization,location.organization.validator.required.organization,location.organization.validator.required.org.pih.warehouse.core.Organization,location.organization.validator.required,validator.required.org.pih.warehouse.core.Location.organization,validator.required.organization,validator.required.org.pih.warehouse.core.Organization,validator.required]; arguments [organization,Location,null,[DEPOT, SUPPLIER]]; default message [Property [{0}] of class [{1}] with value [{2}] does not pass custom validation]

grails.validation.ValidationException: Validation Error(s) occurred during save():
- Field error in object 'org.pih.warehouse.core.Location' on field 'organization': rejected value [null]; codes [org.pih.warehouse.core.Location.organization.validator.error.org.pih.warehouse.core.Location.organization,org.pih.warehouse.core.Location.organization.validator.error.organization,org.pih.warehouse.core.Location.organization.validator.error.org.pih.warehouse.core.Organization,org.pih.warehouse.core.Location.organization.validator.error,location.organization.validator.error.org.pih.warehouse.core.Location.organization,location.organization.validator.error.organization,location.organization.validator.error.org.pih.warehouse.core.Organization,location.organization.validator.error,org.pih.warehouse.core.Location.organization.validator.required.org.pih.warehouse.core.Location.organization,org.pih.warehouse.core.Location.organization.validator.required.organization,org.pih.warehouse.core.Location.organization.validator.required.org.pih.warehouse.core.Organization,org.pih.warehouse.core.Location.organization.validator.required,location.organization.validator.required.org.pih.warehouse.core.Location.organization,location.organization.validator.required.organization,location.organization.validator.required.org.pih.warehouse.core.Organization,location.organization.validator.required,validator.required.org.pih.warehouse.core.Location.organization,validator.required.organization,validator.required.org.pih.warehouse.core.Organization,validator.required]; arguments [organization,Location,null,[DEPOT, SUPPLIER]]; default message [Property [{0}] of class [{1}] with value [{2}] does not pass custom validation]

	at BootStrap.createSupplierLocation(BootStrap.groovy:550)
	at BootStrap$createSupplierLocation.callCurrent(Unknown Source)
	at BootStrap.insertTestFixture(BootStrap.groovy:503)
	at BootStrap$_closure1.doCall(BootStrap.groovy:463)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:251)
	at grails.util.Environment.executeForEnvironment(Environment.java:244)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:220)
	at org.grails.tomcat.InlineExplodedTomcatServer.doStart(InlineExplodedTomcatServer.groovy:112)
	at org.grails.tomcat.InlineExplodedTomcatServer$doStart.callCurrent(Unknown Source)
	at org.grails.tomcat.TomcatServer.start(TomcatServer.groovy:97)
	at grails.web.container.EmbeddableServer$start.call(Unknown Source)
	at _GrailsRun_groovy$_run_closure5_closure12.doCall(_GrailsRun_groovy:158)
	at _GrailsRun_groovy$_run_closure5_closure12.doCall(_GrailsRun_groovy)
	at _GrailsSettings_groovy$_run_closure10.doCall(_GrailsSettings_groovy:280)
	at _GrailsSettings_groovy$_run_closure10.call(_GrailsSettings_groovy)
	at _GrailsRun_groovy$_run_closure5.doCall(_GrailsRun_groovy:149)
	at _GrailsRun_groovy$_run_closure5.call(_GrailsRun_groovy)
	at _GrailsRun_groovy.runInline(_GrailsRun_groovy:116)
	at _GrailsRun_groovy.this$4$runInline(_GrailsRun_groovy)
	at _GrailsRun_groovy$_run_closure1.doCall(_GrailsRun_groovy:59)
	at RunApp$_run_closure1.doCall(RunApp.groovy:33)
	at gant.Gant$_dispatch_closure5.doCall(Gant.groovy:381)
	at gant.Gant$_dispatch_closure7.doCall(Gant.groovy:415)
	at gant.Gant$_dispatch_closure7.doCall(Gant.groovy)
	at gant.Gant.withBuildListeners(Gant.groovy:427)
	at gant.Gant.this$2$withBuildListeners(Gant.groovy)
	at gant.Gant$this$2$withBuildListeners.callCurrent(Unknown Source)
	at gant.Gant.dispatch(Gant.groovy:415)
	at gant.Gant.this$2$dispatch(Gant.groovy)
	at gant.Gant.invokeMethod(Gant.groovy)
	at gant.Gant.executeTargets(Gant.groovy:590)
	at gant.Gant.executeTargets(Gant.groovy:589)
Application context shutting down...
2020-12-26 08:50:59,823 [Thread-20] INFO  support.DefaultLifecycleProcessor  - Stopping beans in phase 2147483647
2020-12-26 08:50:59,826 [Thread-20] INFO  core.QuartzScheduler  - Scheduler DefaultPluginScheduler_$_NON_CLUSTERED paused.
2020-12-26 08:50:59,877 [Thread-20] INFO  core.QuartzScheduler  - Scheduler DefaultPluginScheduler_$_NON_CLUSTERED shutting down.
2020-12-26 08:50:59,877 [Thread-20] INFO  core.QuartzScheduler  - Scheduler DefaultPluginScheduler_$_NON_CLUSTERED paused.
2020-12-26 08:50:59,878 [Thread-20] INFO  core.QuartzScheduler  - Scheduler DefaultPluginScheduler_$_NON_CLUSTERED shutdown complete.
2020-12-26 08:51:00,890 [Thread-20] INFO  ehcache.EhCacheManagerFactoryBean  - Shutting down EHCache CacheManager
2020-12-26 08:51:00,923 [Thread-20] INFO  impl.SessionFactoryImpl  - closing
2020-12-26 08:51:00,924 [Thread-20] INFO  util.NamingHelper  - JNDI InitialContext properties:{}
Application context shutdown.`

Can you help me to fix this,
Thank you.

**Comment by jmiranda** [comment] 2020-12-26 03:16
Thanks for the bug report @tinhbuon1102. This one is probably biting a bunch of people. It's due to the fact that we added a new required property to Location but neglected to update the fixture data in Bootstrap.groovy. I will fix this for good in the upcoming release (0.8.14). 

In the meantime, as a workaround, you can set the following in your openboxes-config.properties file.
{code}
openboxes.fixtures.enabled=false
{code}

**Comment by jmiranda** [comment] 2020-12-28 22:29
Duplicate of #1803

**Comment by jmiranda** [comment] 2021-01-08 05:45
Fixed in 0.8.14 (to be published soon)

**Closed by jmiranda** 2021-01-08 05:45 UTC
Labels: bug
